# Prometheus configuration for experiments platform

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'experiments-platform'

scrape_configs:
  # FastAPI application metrics
  - job_name: 'fastapi'
    static_configs:
      - targets: ['api:8000']
    metrics_path: '/api/v1/metrics'

  # PostgreSQL exporter (if added)
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']

  # Redis exporter (if added)
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']

  # Kafka exporter (if added)
  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka-exporter:9308']

  # ClickHouse metrics
  - job_name: 'clickhouse'
    static_configs:
      - targets: ['clickhouse:8123']
    metrics_path: '/metrics'

  # Node exporter for system metrics
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
